### ISSUE TITLE
design architecture for dev, test, prod environments

### ISSUE THREAD

**Issue by DavidJayBrady** [pawnguild/pawnguild#11]

**Comment by DavidJayBrady** [comment]
dev will be done by local environments

tests are ran by github actions. do we need a test environment?

prod will be on the digital ocean droplet

**Comment by DavidJayBrady** [comment]
test environment (staging) will be on same server as production, just under a different user

**Comment by seriouslysean** [comment]
Is there a better or free solution for this? If there's a bug and staging is taken down it'll bomb prod out.

It would be better to keep them siloed if at all possible.
