### ISSUE TITLE
Redesign homepage to reduce clutter and give better visibility

### ISSUE THREAD

**Issue by seriouslysean** [pawnguild/pawnguild#39]
Some thoughts off the top of my head

- side by side gridded view
    - Steam (takes over 2 spots)
    - Switch, Xbox
    - Ps4, Ps3 (are these shared/can they be combined?)
- Possibly only showing top 5-10 pawns per system 
- Add a view more link at the bottom (maybe and top) to take you to the system specific page
- Add filtering options (default by number of stars and most recently updated?)
    - Alphabetically
    - By rating
    - Last updated
    - By stars
    - By vocation

Alternatively, some sort of color coding by background per platform might be neat-- something like this, https://codepen.io/seriouslysean/pen/WNZOdwP
![image](https://user-images.githubusercontent.com/414475/146689532-3e038cf3-234a-4019-a6c8-5ec112d3cfeb.png)

**Comment by DavidJayBrady** [comment]
I may close this in favor of opening a new mega ticket that is redesigning most of the site, tbd

The ui definitely needs some work!

**Comment by DavidJayBrady** [comment]
- Buttons to each pawn page
    - Recently updated pawn notifications
    - FAQ link
