### ISSUE TITLE
Implement SEO to improve search rankings

### ISSUE THREAD

**Issue by seriouslysean** [pawnguild/pawnguild#40]
Page title
Page descriptions
Image alt tags
OG meta tags (twitter cards, link share images and descriptions)
Favicon sizings

https://moz.com/learn/seo/seo-cheat-sheet

**Comment by DavidJayBrady** [comment]
some keywords that may be good to use
- pawn sharing
- pawn hiring
- pawn list
- dragons dogma
- dark arisen
- rift crystal
- rc
- best way to get rift crystals, rift crystal farm
- platforms supported (xbox, switch, etc)
    - remember: _pages_ rank keywords.. so rank these specifically on the platform pages 


not searched, but my own idea
- bulletin board
- communities that use the tool

**Comment by DavidJayBrady** [comment]
footer with links to communities that use the site. discord/reddit/steam/facebook

**Comment by DavidJayBrady** [comment]
i'll skip multiple size favicons for now. it doesn't seem too pressing to do right away

a part of this is maybe wanting to redesign the favico at some point

**Comment by DavidJayBrady** [comment]
twitter cards partially work in discord (no image)

**Comment by DavidJayBrady** [comment]
page titles, descriptions, alt tags, and twitter cards have all been added now. the faq page and home page will use some of these keywords in future, but more advanced SEO is not a priority, so this will be closed
