### ISSUE TITLE
Allow users to opt in to noindex/nofollow on their pawns, hiding them from search engines

### ISSUE THREAD

**Issue by seriouslysean** [pawnguild/pawnguild#41]
Once the SEO has a pass, this should be a setting in the user's profile (on by default) that they can disable which will hide their pawns from search engines.

https://www.deepcrawl.com/blog/best-practice/noindex-disallow-nofollow/

**Comment by DavidJayBrady** [comment]
@seriouslysean i think if someone registers their pawn on a forum whose goal is to give their pawn exposure, they wouldn't mind showing up directly in google versus being found inside pawnguild. what do you think?

**Comment by DavidJayBrady** [comment]
ive added noindex on all pawns by default... I'd rather the search engine just drive people to the pawn listing pages rather than certain pawns
