### ISSUE TITLE
Add some sort of privacy policy that explains what PawnGuild is doing with the user data (if anything)

### ISSUE THREAD

**Issue by seriouslysean** [pawnguild/pawnguild#42]
Some sort of basic page that tells the user what PawnGuild is doing with their data, if anything. If you're using Google Analytics you need to have one.

https://www.privacypolicies.com/blog/how-write-privacy-policy/
https://www.freeprivacypolicy.com/blog/privacy-policy-google-analytics/

I don't know if those sites are any good but they do seem to make is easier to get the process started.

**Comment by DavidJayBrady** [comment]
https://www.privacypolicytemplate.net/live.php?token=a1o9mUvefq2F6VxazNij4UsBfbo2BYNR
