### ISSUE TITLE
Add form (or link) to create issues/suggestions

### ISSUE THREAD

**Issue by seriouslysean** [pawnguild/pawnguild#50]
It would be nice for users to be able to create issues, whether a feature, bug or suggestion from a form on the site or a link to GitHub.

The ideal solution would be something like this https://gist.github.com/JeffPaine/3145490 that created an issue and then auto tagged with the appropriate label from the form selections (obviously with a captcha or some other way to prevent spam).

**Comment by DavidJayBrady** [comment]
resolved, there is a link in the bottom of the faq to an issue here meant for community feedback
